// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvnqzfgumiiiqwedbxig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bnF6Zmd1bWlpaXF3ZWRieGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTk2NTksImV4cCI6MjA2MDQ5NTY1OX0.GZry8FCSH3o91xOWBiqIaN6l0jGRqBvtPjXoDu5EZik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);