// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srxrwxnuecucpxbrpxhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyeHJ3eG51ZWN1Y3B4YnJweGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDEwNDQsImV4cCI6MjA2MDU3NzA0NH0.wFy5rZ48fs81uF1oMhslYfpipugHI-ahkZFKaakogP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);